using System.Text;
using Microsoft.CodeAnalysis;

namespace Fluid.SourceGenerator
{
    internal static class FactoryEmitter
    {
        public static string Emit(IMethodSymbol methodSymbol, string generatedTemplateTypeFullName)
        {
            // We emit into the containing type's namespace and partial type, implementing the partial method.
            var ns = methodSymbol.ContainingNamespace?.ToDisplayString();
            var containingType = methodSymbol.ContainingType;
            var methodName = methodSymbol.Name;

            var accessibility = containingType.DeclaredAccessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                _ => "internal"
            };

            var typeKind = containingType.TypeKind == TypeKind.Struct ? "struct" : "class";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Fluid;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns))
            {
                sb.Append("namespace ").Append(ns).AppendLine();
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.Append(indent).Append(accessibility).Append(" static partial ").Append(typeKind).Append(' ').Append(containingType.Name).AppendLine();
            sb.Append(indent).AppendLine("{");

            var innerIndent = indent + "    ";
            var fieldName = "__fluidTemplate_" + methodName;

            sb.Append(innerIndent).Append("private static global::Fluid.IFluidTemplate? ").Append(fieldName).AppendLine(";");
            sb.AppendLine();

            sb.Append(innerIndent)
              .Append("public static partial global::Fluid.IFluidTemplate ")
              .Append(methodName)
              .AppendLine("()");

            sb.Append(innerIndent).AppendLine("{");
            sb.Append(innerIndent).Append("    return ").Append(fieldName).Append(" ??= new global::").Append(generatedTemplateTypeFullName).AppendLine("();");
            sb.Append(innerIndent).AppendLine("}");

            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }
    }
}
