using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Fluid.SourceGenerator;

[Generator]
public sealed class MemberAccessorGenerator : IIncrementalGenerator
{
    private const string RegisterExtensionsType = "Fluid.MemberAccessStrategyExtensions";


    private static readonly SymbolDisplayFormat TypeExpressionFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax,
                transform: static (syntaxContext, _) => GetRegistrationType(syntaxContext))
            .Where(static registration => registration is not null)
            .Select(static (registration, _) => registration!);

        var combined = context.CompilationProvider.Combine(registrations.Collect());
        context.RegisterSourceOutput(combined, static (sourceContext, source) => Execute(sourceContext, source.Right));
    }

    private static RegistrationCandidate? GetRegistrationType(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return null;
        }

        if (context.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol methodSymbol)
        {
            return null;
        }

        var method = methodSymbol;

        if (!string.Equals(method.Name, "Register", StringComparison.Ordinal))
        {
            return null;
        }

        if (!string.Equals(method.ContainingType.ToDisplayString(), RegisterExtensionsType, StringComparison.Ordinal))
        {
            return null;
        }

        if (method.TypeArguments.Length == 0)
        {
            return null;
        }

        var registeredType = method.TypeArguments[0];

        if (registeredType is IErrorTypeSymbol || registeredType.TypeKind == TypeKind.TypeParameter)
        {
            return null;
        }

        return new RegistrationCandidate(registeredType);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RegistrationCandidate> registrations)
    {
        if (registrations.IsDefaultOrEmpty)
        {
            return;
        }

        var registeredTypes = new Dictionary<string, ITypeSymbol>(StringComparer.Ordinal);

        foreach (var registration in registrations)
        {
            var typeExpression = registration.Type.ToDisplayString(TypeExpressionFormat);
            if (!registeredTypes.ContainsKey(typeExpression))
            {
                registeredTypes[typeExpression] = registration.Type;
            }
        }

        if (registeredTypes.Count == 0)
        {
            return;
        }

        var registrationsByType = new List<(string TypeExpression, string AccessorName, List<MemberAccess> Members)>();
        var usedAccessorNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var registration in registeredTypes.OrderBy(static x => x.Key, StringComparer.Ordinal))
        {
            var typeExpression = registration.Key;
            var typeSymbol = registration.Value;
            var members = GetMembers(typeSymbol);
            if (members.Count == 0)
            {
                continue;
            }

            var accessorName = CreateAccessorName(typeSymbol, usedAccessorNames);
            registrationsByType.Add((TypeExpression: typeExpression, AccessorName: accessorName, Members: members));
        }

        if (registrationsByType.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();

        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Fluid.SourceGenerated");
        source.AppendLine("{");
        source.AppendLine("    internal static class GeneratedMemberAccessRegistrations");
        source.AppendLine("    {");
        source.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("        internal static void Initialize()");
        source.AppendLine("        {");
        source.AppendLine("            RegisterAll(global::Fluid.TemplateOptions.Default);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        internal static void RegisterAll(global::Fluid.TemplateOptions options)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(options);");
        source.AppendLine("            var strategy = options.MemberAccessStrategy;");
        source.AppendLine();

        foreach (var registration in registrationsByType)
        {
            source.Append("            strategy.Register(typeof(")
                .Append(registration.TypeExpression)
                .Append("), \"*\", new ")
                .Append(registration.AccessorName)
                .AppendLine("());");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();

        foreach (var registration in registrationsByType)
        {
            AppendAccessor(source, registration.AccessorName, registration.TypeExpression, registration.Members);
            source.AppendLine();
        }

        source.AppendLine("}");

        context.AddSource("Fluid.MemberAccessRegistrations.g.cs", source.ToString());
    }

    private static void AppendAccessor(StringBuilder source, string accessorName, string typeExpression, List<MemberAccess> members)
    {
        source.Append("    internal sealed class ").Append(accessorName).AppendLine(" : global::Fluid.IAsyncMemberAccessor");
        source.AppendLine("    {");
        source.AppendLine("        public object Get(object obj, string name, global::Fluid.TemplateContext ctx)");
        source.AppendLine("        {");
        source.Append("            var typed = (").Append(typeExpression).AppendLine(")obj;");
        source.AppendLine("            var comparer = ctx.Options.ModelNamesComparer;");
        source.AppendLine();

        foreach (var member in members)
        {
            source.Append("            if (comparer.Equals(name, \"")
                .Append(member.Name)
                .AppendLine("\"))");
            source.AppendLine("            {");
            source.Append("                return ").Append(member.Expression).AppendLine(";");
            source.AppendLine("            }");
        }

        source.AppendLine();
        source.AppendLine("            return null;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public async global::System.Threading.Tasks.Task<object> GetAsync(object obj, string name, global::Fluid.TemplateContext ctx)");
        source.AppendLine("        {");
        source.Append("            var typed = (").Append(typeExpression).AppendLine(")obj;");
        source.AppendLine("            var comparer = ctx.Options.ModelNamesComparer;");
        source.AppendLine();

        foreach (var member in members)
        {
            source.Append("            if (comparer.Equals(name, \"")
                .Append(member.Name)
                .AppendLine("\"))");
            source.AppendLine("            {");

            switch (member.AsyncKind)
            {
                case AsyncKind.Task:
                    source.Append("                var task = ").Append(member.Expression).AppendLine(";");
                    source.AppendLine("                await task.ConfigureAwait(false);");
                    source.AppendLine("                return task.Result;");
                    break;
                case AsyncKind.ValueTask:
                    source.Append("                var valueTask = ").Append(member.Expression).AppendLine(";");
                    source.AppendLine("                return await valueTask.ConfigureAwait(false);");
                    break;
                default:
                    source.Append("                return ").Append(member.Expression).AppendLine(";");
                    break;
            }

            source.AppendLine("            }");
        }

        source.AppendLine();
        source.AppendLine("            return null;");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static List<MemberAccess> GetMembers(ITypeSymbol typeSymbol)
    {
        var members = new List<MemberAccess>();
        var names = new HashSet<string>(StringComparer.Ordinal);

        foreach (var property in EnumerateProperties(typeSymbol))
        {
            if (!names.Add(property.Name))
            {
                continue;
            }

            var memberName = EscapeIdentifier(property.Name);
            if (memberName is null)
            {
                continue;
            }

            var expression = property.IsStatic
                ? $"{typeSymbol.ToDisplayString(TypeExpressionFormat)}.{memberName}"
                : $"typed.{memberName}";

            members.Add(new MemberAccess(property.Name, expression, GetAsyncKind(property.Type)));
        }

        foreach (var field in EnumerateFields(typeSymbol))
        {
            if (!names.Add(field.Name))
            {
                continue;
            }

            var memberName = EscapeIdentifier(field.Name);
            if (memberName is null)
            {
                continue;
            }

            var expression = field.IsStatic
                ? $"{typeSymbol.ToDisplayString(TypeExpressionFormat)}.{memberName}"
                : $"typed.{memberName}";

            members.Add(new MemberAccess(field.Name, expression, GetAsyncKind(field.Type)));
        }

        foreach (var method in EnumerateMethods(typeSymbol))
        {
            if (!names.Add(method.Name))
            {
                continue;
            }

            var memberName = EscapeIdentifier(method.Name);
            if (memberName is null)
            {
                continue;
            }

            var expression = method.IsStatic
                ? $"{typeSymbol.ToDisplayString(TypeExpressionFormat)}.{memberName}()"
                : $"typed.{memberName}()";

            members.Add(new MemberAccess(method.Name, expression, GetAsyncKind(method.ReturnType)));
        }

        return members;
    }

    private static IEnumerable<IPropertySymbol> EnumerateProperties(ITypeSymbol typeSymbol)
    {
        foreach (var symbol in EnumerateMembers(typeSymbol).OfType<IPropertySymbol>())
        {
            if (symbol.IsIndexer || symbol.GetMethod is null)
            {
                continue;
            }

            if (symbol.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            yield return symbol;
        }
    }

    private static IEnumerable<IFieldSymbol> EnumerateFields(ITypeSymbol typeSymbol)
    {
        foreach (var symbol in EnumerateMembers(typeSymbol).OfType<IFieldSymbol>())
        {
            if (symbol.DeclaredAccessibility != Accessibility.Public || symbol.IsConst)
            {
                continue;
            }

            yield return symbol;
        }
    }

    private static IEnumerable<IMethodSymbol> EnumerateMethods(ITypeSymbol typeSymbol)
    {
        foreach (var symbol in EnumerateMembers(typeSymbol).OfType<IMethodSymbol>())
        {
            if (symbol.MethodKind != MethodKind.Ordinary || symbol.IsGenericMethod)
            {
                continue;
            }

            if (symbol.DeclaredAccessibility != Accessibility.Public || symbol.Parameters.Length != 0 || symbol.ReturnsVoid)
            {
                continue;
            }

            if (symbol.ContainingType.SpecialType == SpecialType.System_Object)
            {
                continue;
            }

            yield return symbol;
        }
    }

    private static IEnumerable<ISymbol> EnumerateMembers(ITypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeKind == TypeKind.Interface)
        {
            foreach (var member in typeSymbol.GetMembers())
            {
                yield return member;
            }

            foreach (var iface in typeSymbol.AllInterfaces)
            {
                foreach (var member in iface.GetMembers())
                {
                    yield return member;
                }
            }

            yield break;
        }

        for (var current = typeSymbol; current is not null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            foreach (var member in current.GetMembers())
            {
                yield return member;
            }
        }
    }

    private static AsyncKind GetAsyncKind(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType || !namedType.IsGenericType)
        {
            return AsyncKind.None;
        }

        var containingNamespace = namedType.ContainingNamespace?.ToDisplayString();
        if (!string.Equals(containingNamespace, "System.Threading.Tasks", StringComparison.Ordinal))
        {
            return AsyncKind.None;
        }

        return namedType.Name switch
        {
            "Task" => AsyncKind.Task,
            "ValueTask" => AsyncKind.ValueTask,
            _ => AsyncKind.None
        };
    }

    private static string CreateAccessorName(ITypeSymbol typeSymbol, HashSet<string> usedAccessorNames)
    {
        var baseName = typeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var accessorNameBuilder = new StringBuilder(baseName.Length + 16);

        for (var i = 0; i < baseName.Length; i++)
        {
            var c = baseName[i];
            accessorNameBuilder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }

        accessorNameBuilder.Append("_GeneratedMemberAccessor");
        var accessorName = accessorNameBuilder.ToString();

        if (usedAccessorNames.Add(accessorName))
        {
            return accessorName;
        }

        var suffix = 2;
        while (!usedAccessorNames.Add(accessorName + suffix))
        {
            suffix++;
        }

        return accessorName + suffix;
    }

    private static string? EscapeIdentifier(string identifier)
    {
        if (!SyntaxFacts.IsValidIdentifier(identifier))
        {
            return null;
        }

        return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ? "@" + identifier : identifier;
    }

    private sealed record RegistrationCandidate(ITypeSymbol Type);

    private sealed record MemberAccess(string Name, string Expression, AsyncKind AsyncKind);

    private enum AsyncKind
    {
        None,
        Task,
        ValueTask
    }
}
